"""create_users_and_houses

Revision ID: 8d6d52d5510a
Revises: 
Create Date: 2026-05-14 23:30:57.846376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6d52d5510a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('min_area', sa.Float(), nullable=True),
    sa.Column('max_area', sa.Float(), nullable=True),
    sa.Column('avg_area', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=20), nullable=True),
    sa.Column('price_flag', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_place'), 'houses', ['place'], unique=False)
    op.create_index(op.f('ix_houses_price'), 'houses', ['price'], unique=False)
    op.create_index(op.f('ix_houses_property_type'), 'houses', ['property_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_houses_property_type'), table_name='houses')
    op.drop_index(op.f('ix_houses_price'), table_name='houses')
    op.drop_index(op.f('ix_houses_place'), table_name='houses')
    op.drop_table('houses')
    # ### end Alembic commands ###
